export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const OTP_BY_MAIL_START = 'OTP_BY_MAIL_START';
export const OTP_BY_MAIL_SUCCESS = 'OTP_BY_MAIL_SUCCESS';
export const OTP_BY_MAIL_FAIL = 'OTP_BY_MAIL_FAIL';

export const OTP_VERIFICATION_START = 'OTP_VERIFICATION_START';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAIL = 'OTP_VERIFICATION_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_OTP_FAIL = 'AUTH_OTP_FAIL';

export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAIL = 'CATEGORY_FAIL';

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';